"use client";

import { CheckCircle2, ChevronDown, CircleAlert, FileCheck2 } from "lucide-react";
import { useState } from "react";
import { getCategoryConfig } from "@/data/product-categories";
import { calculateReadiness, calculateReceivable } from "@/lib/factoring-engine";
import { formatCurrency } from "@/lib/format";
import { ApplicationDraft, ContractAnalysisResult } from "@/lib/types";

type DraftChange = <K extends keyof ApplicationDraft>(key: K, value: ApplicationDraft[K]) => void;

export function ReceivableReadiness({ draft, analysis, errors, onChange }: { draft: ApplicationDraft; analysis: ContractAnalysisResult; errors: Record<string, string>; onChange: DraftChange }) {
  const [showFormula, setShowFormula] = useState(false);
  const documents = Object.values(draft.documents).filter(Boolean);
  const receivable = calculateReceivable({ acceptedSupplyAmount: Number(draft.acceptedSupplyAmount), returnsAmount: Number(draft.returnsAmount), holdsAmount: Number(draft.holdsAmount), desiredFinancingAmount: Number(draft.desiredFinancingAmount), confirmationDate: draft.confirmationDate, paymentTermDays: Number(draft.paymentTermDays) });
  const readiness = calculateReadiness(draft.productCategory, documents, analysis);
  const category = getCategoryConfig(draft.productCategory);
  const numericField = (key: "acceptedSupplyAmount" | "returnsAmount" | "holdsAmount" | "desiredFinancingAmount", label: string) => <label className="block"><span className="mb-2 block text-sm font-semibold text-ink">{label}</span><span className="relative block"><input className="control pr-10" type="number" min="0" value={draft[key]} onChange={(event) => onChange(key, event.target.value)} /><span className="pointer-events-none absolute inset-y-0 right-3 flex items-center text-xs text-slate-500">₸</span></span>{errors[key] && <span className="mt-1 block text-xs font-medium text-red-700">{errors[key]}</span>}</label>;

  return <div><div className="flex items-start gap-4"><span className="font-display text-3xl text-moss-500">03</span><div><p className="eyebrow mb-1">Расчёт и документы</p><h2 className="text-xl font-semibold text-ink">Подтверждённое требование</h2><p className="mt-1 text-sm leading-6 text-muted">Укажите только фактические корректировки. Остальное FlowFactor рассчитывает автоматически.</p></div></div>
    <div className="mt-7 grid gap-7 lg:grid-cols-[1fr_.9fr]"><section><div className="grid gap-5 sm:grid-cols-2">{numericField("acceptedSupplyAmount", "Принятые поставки")}{numericField("returnsAmount", "Возвраты")}{numericField("holdsAmount", "Удержания покупателя")}<label className="block"><span className="mb-2 block text-sm font-semibold text-ink">Дата подтверждения поставки</span><input className="control" type="date" value={draft.confirmationDate} onChange={(event) => onChange("confirmationDate", event.target.value)} />{errors.confirmationDate && <span className="mt-1 block text-xs font-medium text-red-700">{errors.confirmationDate}</span>}</label>{numericField("desiredFinancingAmount", "Желаемая сумма финансирования")}</div>
      <div className="mt-6 grid gap-px overflow-hidden border border-line bg-line sm:grid-cols-3"><Metric label="Подтверждённое требование" value={formatCurrency(receivable.confirmedReceivable)} /><Metric label="Предварительный максимум" value={formatCurrency(receivable.availableFinancing)} /><Metric label="Ожидаемая дата оплаты" value={receivable.dueDate ? new Intl.DateTimeFormat("ru-RU").format(new Date(`${receivable.dueDate}T00:00:00`)) : "Нужна дата"} /></div>
      <button type="button" className="mt-3 inline-flex items-center gap-2 text-xs font-semibold text-moss-700" onClick={() => setShowFormula((value) => !value)}>Как рассчитано? <ChevronDown className={`h-4 w-4 transition ${showFormula ? "rotate-180" : ""}`} /></button>{showFormula && <p className="mt-3 border-l-2 border-moss-400 pl-3 text-xs leading-5 text-slate-600">Требование = принятые поставки − возвраты − удержания. Предварительный максимум в MVP — до 95% требования, но не больше желаемой суммы. Комиссия появится только в конкретном предложении партнёра.</p>}</section>
      <aside className="border border-line bg-slate-50/60 p-5"><div className="flex items-center justify-between gap-3"><div><p className="eyebrow mb-1">Предварительная готовность</p><h3 className="text-xl font-semibold text-ink">{readiness.score} из 100</h3></div><span className="flex h-12 w-12 items-center justify-center rounded-full bg-white text-moss-700 ring-1 ring-moss-200"><FileCheck2 className="h-5 w-5" /></span></div><p className="mt-3 text-sm text-slate-600">Документы: {readiness.documentCompleteness}% · категория «{category.label}»</p><div className="mt-5"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Нужно добавить</p>{readiness.missingDocuments.length ? <ul className="mt-2 space-y-2">{readiness.missingDocuments.map((item) => <li key={item} className="flex gap-2 text-sm text-amber-900"><CircleAlert className="mt-0.5 h-4 w-4 shrink-0" />{item}</li>)}</ul> : <p className="mt-2 flex gap-2 text-sm text-moss-800"><CheckCircle2 className="h-4 w-4" /> Основной пакет собран</p>}</div><div className="mt-5"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Риски категории</p><ul className="mt-2 space-y-2">{readiness.risks.map((item) => <li key={item} className="flex gap-2 text-sm text-slate-600"><span aria-hidden="true">•</span>{item}</li>)}</ul></div><p className="mt-5 border-t border-line pt-4 text-xs leading-5 text-slate-500">{readiness.preliminaryConclusion} Финальное решение принимает партнёр.</p></aside></div>
  </div>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="bg-paper p-4"><p className="text-[11px] text-slate-500">{label}</p><p className="mt-2 text-lg font-semibold text-ink">{value}</p></div>; }
